namespace Siniestros360.Contracts.Events;

public sealed record ClaimReported(Guid ClaimId, string InsuredId, string Folio, string PolicyNumber, string VehiclePlate, string IncidentType, decimal Latitude, decimal Longitude, bool RequiresAmbulance, DateTimeOffset ReportedAt);
public sealed record ClaimStatusChanged(Guid ClaimId, string PreviousStatus, string NewStatus, long Version, DateTimeOffset ChangedAt);
public sealed record ClaimClosed(Guid ClaimId, DateTimeOffset ClosedAt);
public sealed record ClaimCancelled(Guid ClaimId, string Reason, DateTimeOffset CancelledAt);
public sealed record PolicyValidationRequested(Guid ClaimId, string PolicyNumber, DateTimeOffset RequestedAt);
public sealed record PolicyValidationCompleted(Guid ClaimId, string PolicyNumber, string CoverageStatus, string? Reason, DateTimeOffset ValidatedAt);
public sealed record PolicyValidationFailed(Guid ClaimId, string PolicyNumber, string ErrorCode, string ErrorMessage, DateTimeOffset FailedAt);
public sealed record PolicyValidationUnavailable(Guid ClaimId, string PolicyNumber, string Reason, DateTimeOffset OccurredAt);
public sealed record AdjusterAssignmentRequested(Guid ClaimId, decimal Latitude, decimal Longitude, DateTimeOffset RequestedAt);
public sealed record AdjusterAssigned(Guid ClaimId, Guid AdjusterId, double DistanceKm, DateTimeOffset AssignedAt, DateTimeOffset EstimatedArrivalAt);
public sealed record NoAdjusterAvailable(Guid ClaimId, string Reason, DateTimeOffset OccurredAt);
public sealed record ClaimReassignmentRequested(Guid ClaimId, string Reason, DateTimeOffset RequestedAt);
public sealed record ClaimReassigned(Guid ClaimId, Guid PreviousAdjusterId, Guid NewAdjusterId, string Reason, DateTimeOffset ReassignedAt);
public sealed record AdjusterRegistered(Guid AdjusterId, string DisplayName, DateTimeOffset RegisteredAt);
public sealed record AdjusterAvailabilityChanged(Guid AdjusterId, bool IsAvailable, DateTimeOffset ChangedAt);
public sealed record AdjusterStatusChanged(Guid AdjusterId, string PreviousStatus, string NewStatus, DateTimeOffset ChangedAt);
public sealed record AdjusterArrived(Guid ClaimId, Guid AdjusterId, DateTimeOffset ArrivedAt);
public sealed record AdjusterServiceStarted(Guid ClaimId, Guid AdjusterId, DateTimeOffset StartedAt);
public sealed record AdjusterServiceCompleted(Guid ClaimId, Guid AdjusterId, DateTimeOffset CompletedAt);
public sealed record AdjusterLocationUpdated(Guid AdjusterId, decimal Latitude, decimal Longitude, double? SpeedKmh, double? Heading, long Sequence, DateTimeOffset CapturedAt);
public sealed record AdjusterGpsStaleDetected(Guid AdjusterId, DateTimeOffset LastSeenAt, DateTimeOffset DetectedAt);
public sealed record SlaStageStarted(Guid ClaimId, string Stage, DateTimeOffset StartedAt, DateTimeOffset DueAt);
public sealed record SlaWarningRaised(Guid ClaimId, string WarningType, string Message, DateTimeOffset RaisedAt);
public sealed record SlaBreached(Guid ClaimId, string SlaType, string Message, DateTimeOffset BreachedAt);
public sealed record ClaimEscalated(Guid ClaimId, string Reason, DateTimeOffset EscalatedAt);
public sealed record DocumentUploaded(Guid DocumentId, Guid ClaimId, string FileName, string ContentType, long SizeBytes, DateTimeOffset UploadedAt);
public sealed record DocumentDeleted(Guid DocumentId, Guid ClaimId, DateTimeOffset DeletedAt);
